image: node:latest
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

before_script:
  - echo "run test"

stages:
  - build

build:
  stage: build
  script:
  - npm install